services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
